[package]
name = "elang_interpreter"
version = "0.1.0"
edition = "2021"

[lib]
name = "elang_interpreter"
path = "src/lib.rs"

[[bin]]
name = "elang"
path = "src/main.rs"

[dependencies]
lexpr = "0.2.7"

[dev-dependencies]
tempfile = "3.10.1"

[[test]]
name = "spec"
path = "tests/spec.rs"
